baseURL = "http://example.org/"
languageCode = "en-us"
title = "Harrison Van Roy"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "ğŸ¡"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Notes"
    pre = "ğŸ—’"
    url = "/notes/"
    weight = 2

[params]
  custom_css = ["/css/style.css"]